stages:
  - lint
  - test
  - publish
  - deploy

# select the autoscaled Gitlab runner
default:
  tags:
    - autoscaled

before_script:
  - python -m pip install --upgrade pip
  - python -m pip install hatch

lint:
  stage: lint
  script:
    - python -m hatch run pip install pre-commit pyproject-flake8
    - python -m hatch run pre-commit install
    - python -m hatch run pre-commit run --all-files

test:
  stage: test
  parallel:
    matrix:
      - PYTHON_VERSION:
        - '3.10'
        - '3.11'
  image: python:${PYTHON_VERSION}
  script:
    - python3 -m hatch -v run test

test-notebooks:
  image: python:3.11
  stage: test
  script:
    - "command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client libcairo2-dev -y )"
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - python -m hatch -v run test-notebooks

test-docs:
  image: python:3.11
  stage: test
  script:
    - python -m hatch -v -e docs run test

publish:
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - python -m hatch build
    - python -m hatch publish

pages:
  stage: test
  image: python:3.11
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - python -m hatch -v run docs:build --site-dir public
