variables:
  #HATCH_INDEX_USER: $PYPI_USERNAME
  #HATCH_INDEX_AUTH: $PYPI_PASSWORD
  #HATCH_INDEX_REPO: $PYPI_URL
  #SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY
  #DOCKER_NAMESPACE: docker/project/namespace
  #DOCKER_PACKAGE_NAME: my-package
  #CLUSTER_MODULE_NAME: mypackage

stages:
  - lint
  - test
  - publish
  - deploy

# select the autoscaled Gitlab runner
default:
  tags:
    - autoscaled

before_script:
  - python -m pip install --upgrade pip
  - python -m pip install hatch

lint:
  stage: lint
  script:
    - pip install pre-commit pyproject-flake8
    - pre-commit install
    - pre-commit run --all-files

test:
  stage: test
  parallel:
    matrix:
      - PYTHON_VERSION:
        - '3.10'
        - '3.11'
  image: python:${PYTHON_VERSION}
  script:
    - python3 -m hatch -v run test

test-notebooks:
  image: python:3.11
  stage: test
  script:
    - "command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client libcairo2-dev -y )"
    - eval $(ssh-agent -s)
    #- echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    #- ssh-keyscan gitlab.pasqal.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - python -m hatch -v run test-notebooks

test-docs:
  image: python:3.11
  stage: test
  script:
    - python -m hatch -v -e docs run test

publish:
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - python -m hatch build
    - python -m hatch publish

pages:
  stage: test
  image: python:3.11
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - python -m hatch -v run docs:build --site-dir public
