repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

-   repo: https://github.com/ambv/black
    rev: 24.8.0
    hooks:
      - id: black

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.5.6"
    hooks:
      - id: ruff
        args: [--fix]

-   repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: ./.mypy_script
        language: script
        require_serial: true
