site_name: pulser-diff
repo_url: "https://gitlab.pasqal.com/pqs/pulser-diff"
repo_name: "pulser-diff"

nav:
  - Notebooks:
    - index.md
    - Basic usage: basic_usage.ipynb

theme:
  name: material
  features:
  - content.code.annotate
  - content.action.view
  - content.action.edit
  - navigation.tabs
  - navigation.indexes
  - navigation.sections
  - content.code.copy

  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: light green
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: light green
    toggle:
      icon: material/weather-night
      name: Switch to light mode

markdown_extensions:
- admonition  # for notes
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences

plugins:
- search
- section-index
- markdown-exec
- mkdocs-jupyter:
    ignore_h1_titles: True
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          show_root_toc_entry: false
          heading_level: 3
          merge_init_into_class: true
          docstring_section_style: spacy
          filters:
            - "!^_"  # exlude all members starting with _
            - "^__init__$"  # but always include __init__ modules and methods

watch:
  - pulser_diff

extra:
 version:
   provider: mike

# To get nice tabs
extra_css:
- css/mkdocstrings.css

# For mathjax
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - javascripts/mathjax.js
