from __future__ import annotations

ATOL_WF = 1e-2
ATOL_EXPV_DP = 1e-3
ATOL_EXPV_KRYLOV = 1e-2
ATOL_DERIV_TIME = 5e-2
ATOL_DERIV_PARAM = 1e-3
ATOL_DERIV_COORD = 1e-2
ATOL_OPTIM = 5e-2
ATOL_OPTIM_COORD = 1e-3
EPS_PARAM = 1e-4
RTOL_NOISE = 5e-3
ATOL_NOISE = 5e-3
ATOL_ENV = 5e-2
